require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoroughsController do

  # This should return the minimal set of attributes required to create a valid
  # Borough. As you add validations to Borough, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all boroughs as @boroughs" do
      borough = Borough.create! valid_attributes
      get :index
      assigns(:boroughs).should eq([borough])
    end
  end

  describe "GET show" do
    it "assigns the requested borough as @borough" do
      borough = Borough.create! valid_attributes
      get :show, :id => borough.id.to_s
      assigns(:borough).should eq(borough)
    end
  end

  describe "GET new" do
    it "assigns a new borough as @borough" do
      get :new
      assigns(:borough).should be_a_new(Borough)
    end
  end

  describe "GET edit" do
    it "assigns the requested borough as @borough" do
      borough = Borough.create! valid_attributes
      get :edit, :id => borough.id.to_s
      assigns(:borough).should eq(borough)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Borough" do
        expect {
          post :create, :borough => valid_attributes
        }.to change(Borough, :count).by(1)
      end

      it "assigns a newly created borough as @borough" do
        post :create, :borough => valid_attributes
        assigns(:borough).should be_a(Borough)
        assigns(:borough).should be_persisted
      end

      it "redirects to the created borough" do
        post :create, :borough => valid_attributes
        response.should redirect_to(Borough.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved borough as @borough" do
        # Trigger the behavior that occurs when invalid params are submitted
        Borough.any_instance.stub(:save).and_return(false)
        post :create, :borough => {}
        assigns(:borough).should be_a_new(Borough)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Borough.any_instance.stub(:save).and_return(false)
        post :create, :borough => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested borough" do
        borough = Borough.create! valid_attributes
        # Assuming there are no other boroughs in the database, this
        # specifies that the Borough created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Borough.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => borough.id, :borough => {'these' => 'params'}
      end

      it "assigns the requested borough as @borough" do
        borough = Borough.create! valid_attributes
        put :update, :id => borough.id, :borough => valid_attributes
        assigns(:borough).should eq(borough)
      end

      it "redirects to the borough" do
        borough = Borough.create! valid_attributes
        put :update, :id => borough.id, :borough => valid_attributes
        response.should redirect_to(borough)
      end
    end

    describe "with invalid params" do
      it "assigns the borough as @borough" do
        borough = Borough.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Borough.any_instance.stub(:save).and_return(false)
        put :update, :id => borough.id.to_s, :borough => {}
        assigns(:borough).should eq(borough)
      end

      it "re-renders the 'edit' template" do
        borough = Borough.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Borough.any_instance.stub(:save).and_return(false)
        put :update, :id => borough.id.to_s, :borough => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested borough" do
      borough = Borough.create! valid_attributes
      expect {
        delete :destroy, :id => borough.id.to_s
      }.to change(Borough, :count).by(-1)
    end

    it "redirects to the boroughs list" do
      borough = Borough.create! valid_attributes
      delete :destroy, :id => borough.id.to_s
      response.should redirect_to(boroughs_url)
    end
  end

end
